# -*- coding: utf-8 -*-
"""LabAssignment2_PalaknNandkeuliar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOCySSb9bKrs8AA7u55sxDXRJDOgmU64
"""

# ============================================================
# FACEBOOK DATA ANALYSIS PROJECT
# Author: Palak Nandkeuliar
# Course: Data110
# Description:
# This project performs descriptive statistical analysis
# and data visualization on Facebook datasets (.txt, .csv, .xlsx).
# ============================================================


# ============================
# 1. IMPORT REQUIRED LIBRARIES
# ============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option('display.max_columns', None)



# ============================================================
# 2. DATA ACCESS
# Load the Facebook datasets (.txt, .csv, .xlsx)
# ============================================================

# File paths (adjust if running locally)
txt_file = "Facebook Friends.txt"
csv_file = "Facebook Friends.csv"
xlsx_file = "Facebook Friends.xlsx"

# Read TXT file
df_txt = pd.read_csv("/content/Facebook Friends.txt", sep="\t", encoding='utf-16')

# Read CSV file
df_csv = pd.read_csv("/content/Facebook Friends.csv")

# Read Excel file
df_excel = pd.read_excel("/content/Facebook Friends.xlsx")

# Display shape comparison
print("TXT Shape:", df_txt.shape)
print("CSV Shape:", df_csv.shape)
print("Excel Shape:", df_excel.shape)

# Compare first few rows
print("\nTXT Head:")
print(df_txt.head())

print("\nCSV Head:")
print(df_csv.head())

print("\nExcel Head:")
print(df_excel.head())

# ------------------------------------------------------------
# DOES SOURCE TYPE MATTER?
# ------------------------------------------------------------
"""
If data is formatted consistently, the content remains the same.
However, differences may appear due to:
- Delimiters (tab vs comma)
- Encoding issues
- Numeric formatting (e.g., commas in numbers like "1,689")
- Automatic type detection differences
Excel often preserves formatting better.
"""



# ============================================================
# 3. DATA EXAMINATION (Using Excel DataFrame Only)
# ============================================================

df = df_excel.copy()

# Check column names
print("\nColumn Names:")
print(df.columns)

# View top rows
print("\nTop 5 Rows:")
print(df.head())

# View bottom rows
print("\nBottom 5 Rows:")
print(df.tail())

# Data types
print("\nData Types:")
print(df.dtypes)

# Check for missing values
print("\nMissing Values Per Column:")
print(df.isnull().sum())

# Check total missing values
print("\nTotal Missing Values:", df.isnull().sum().sum())



# ============================================================
# 4. DATA CLEANING
# Remove commas in numeric columns (e.g., Friends column)
# ============================================================

# Convert object columns that contain numbers with commas
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace(',', '')
        df[col] = pd.to_numeric(df[col], errors='ignore')

print("\nData Types After Cleaning:")
print(df.dtypes)



# ============================================================
# 5. DESCRIPTIVE STATISTICS
# ============================================================

print("\nDescriptive Statistics:")
print(df.describe())

"""
describe() provides:
- count: non-missing observations
- mean: average value
- std: standard deviation
- min: minimum value
- 25%: first quartile
- 50%: median
- 75%: third quartile
- max: maximum value

These describe central tendency and spread of the data.
"""



# ============================================================
# 6. DATA VISUALIZATION
# Histogram and Frequency Plots
# ============================================================

# Select numeric columns only
numeric_cols = df.select_dtypes(include=[np.number]).columns

# ------------------------
# HISTOGRAMS
# ------------------------
for col in numeric_cols:
    plt.figure()
    df[col].hist(bins=20)
    plt.title(f"Histogram of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

# ------------------------
# FREQUENCY PLOT (BAR PLOT)
# Example for Gender column if binary
# ------------------------

if "Gender" in df.columns:
    plt.figure()
    df["Gender"].value_counts().plot(kind="bar")
    plt.title("Frequency Plot of Gender")
    plt.xlabel("Gender")
    plt.ylabel("Count")
    plt.show()


"""
How visualization helps:
- Identifies skewness
- Detects outliers
- Shows distribution shape
- Highlights dominant categories
- Helps understand spread and variability
"""



# ============================================================
# 7. SAVE OUTPUT AS HTML
# ============================================================

# Export descriptive statistics as HTML
df.describe().to_html("descriptive_statistics.html")

# Save entire cleaned dataset
df.to_html("facebook_cleaned_data.html")

print("\nHTML files saved successfully.")